In [48]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import os
import sys
import json

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
from TextItem import TextItem

In [50]:
save_folder = "STEP 1 - RAW_JSON_TO_CSV"

In [113]:
jsonfile = "../graphql/downloads/sports/2019_Q1_0.json"

In [117]:
with open(jsonfile, 'r', encoding="utf8") as f:
    f = json.load(f)
    edges = f["events"]["edges"]

    entities = []
    entitiesNoLimit = []
    texts = []

    for node in edges:
        data = TextItem(node, limit_to_relations=True)
        dataNoLimit = TextItem(node, limit_to_relations=False)
        ents = data.get_entities_object()
        entsNoLimit = dataNoLimit.get_entities_object()
        txts = data.get_text_object()

        entities.append(pd.DataFrame(ents))
        entitiesNoLimit.append(pd.DataFrame(entsNoLimit))

        #texts.append(txts)
        
        #print(pd.DataFrame(ents))
df = pd.concat(entities)
dfNoLim = pd.concat(entitiesNoLimit)
e = list(df.name.unique())
eNoLim = list(dfNoLim.name.unique())
print("{} uniq ents".format(len(e)))
print("{} uniq ents (NO LIM!)".format(len(eNoLim)))
print("Ents missing from limited...")
print([x for x in eNoLim if x not in e])

459 uniq ents
693 uniq ents (NO LIM!)
Ents missing from limited...
['left-wing', 'match', 'swing music', 'country', 'universal quantification', 'human mouth', 'month', 'parking lot', 'nature reserve', 'thought', 'existence', 'meals', 'human', 'business', 'Shell shock', 'country music', 'game', 'array data structure', 'eighteen-year-old', 'cover version', 'Go', 'sales', 'rock music', 'partnership', 'political campaign', 'advertising', 'competition', 'harbor', 'research proposal', 'contract', 'will', 'supporter', 'corporate social responsibility', 'gramophone record', 'diagram', 'credit', 'happiness', 'track and field', 'peat', 'gambling', 'December', 'common cold', "hors d'oeuvre", 'liquid-crystal display', 'photograph', 'light-emitting diode', 'Wi-Fi', 'Wide Ultra Extended Graphics Array+', 'mid-range speaker', 'computer data storage', 'kra', 'graphics processing unit', 'IPS panel', 'fasting', 'random-access memory', 'read-only memory', 'sequel', 'semi-trailer truck', 'corporate title', 'high heels', 'human nose', 'ellipsis', 'disgust', 'dialogue', 'right-wing', 'prime number', 'double-precision floating-point format', 'fad', 'inch', 'fashion', 'necktie', 'dressing room', 'short story', 'percent', 'electric current', 'N T Rama Rao filmography', 'entity', 'stock', 'investment', 'revenue', 'week', 'magnetic-core memory', 'storey', 'military tactics', 'target market', 'software as a service', 'pole position', 'octave', 'tugboat', 'evidence', 'October', 'plug-in', 'hyphen', 'payment', 'weft', 'government agency', 'logarithm', 'shopping mall', 'tourism', 'Wednesday', 'ice hockey', 'check mark', 'January', 'partitur', 'gift', 'steady state', 'twenty-two year old', 'tuberculosis', 'crime', 'emergency department', 'Jötnar', 'intellectual property', 'mechanical load', 'quarter-final', 'BREAK', 'twenty-seven year old', 'seal hunting', 'conflict', 'scheduler', 'metropolitan area', 'transport', 'dawn', 'association football', 'lip', 'text messaging', 'academic degree', 'element', 'general officer', 'atonement in Christianity', 'contract bridge', 'spirit level', 'metre', 'primary election', 'pressure', 'human height', 'quantity', 'Olympic Games', 'bobsleigh', 'letter case', 'equestrianism', 'Trojan horse', 'brassiere', 'string', 'Greenwich Mean Time', 'ear', 'bling-bling', 'cosmetics', 'woman on top', 'brown hair', 'lawyer', 'joint venture', 'child', 'foot', 'parent', 'concrete masonry unit', 'male organism', 'laughter', 'panel discussion', 'Doctor of Philosophy', 'memorandum', 'filename extension', 'memorandum of understanding', 'facilitator', 'five-a-side football', 'computer program', 'offer and acceptance', 'processor register', 'female organism', 'mean', 'centennial', 'user guide', 'forest', 'résumé', 'golf', 'wisdom', 'foreign exchange market', 'motorsport', 'gymnasium', 'hard disk drive', 'computer monitor', 'artificial satellite', 'luxury good', 'outer space', 'mixed martial arts', 'colonel', 'twenty-one year old', 'device driver', 'parser', 'disaster', 't-shirt', 'airline hub', 'trade', 'mystery fiction', 'receiver operating characteristic', 'exponential function', 'health care', 'money', 'trade union', 'computing platform', 'Internet forum', 'racket', 'earthquake', 'electric charge', 'death by burning', 'sole fish', 'wage', 'marketplace', 'computer vulnerability', 'building', 'software requirements specification', 'basement', 'Pacific Ocean', 'baby', 'arm', 'menstruation', 'American football', 'natural watercourse', '0-2-2', '6-2-0', 'cogwheel', 'rip current', 'behavior', 'cattle', 'product', 'Color Graphics Adapter', 'nun', 'mother', 'half sister', 'sailboat', 'couch', 'color', 'television advertisement', 'rapping', 'sexual intercourse']

In [119]:
df.references.uniq

,id,entity_id,name,description,text,references
0,IjJlYWU1MDU0MThkZDJiNzNhNDZmOTY3OWY1N2JlZTUxMT...,Q6396707,Kevin Kisner,professional golfer,He covers $T$ writes poetry about Rory McIlroy...,"golfer,Kevin James Kisner,human,golf"
1,IjJlYWU1MDU0MThkZDJiNzNhNDZmOTY3OWY1N2JlZTUxMT...,Q1593292,World Golf Championships,One of four golf tournaments,The semifinals and finals of the 2019 $T$ Tech...,"The World Golf Championships,golf,WGC"
2,IjJlYWU1MDU0MThkZDJiNzNhNDZmOTY3OWY1N2JlZTUxMT...,Q1593292,World Golf Championships,One of four golf tournaments,Sergio Garcia fell as well -- to Matt Kuchar -...,"The World Golf Championships,golf,WGC"
3,IjJlYWU1MDU0MThkZDJiNzNhNDZmOTY3OWY1N2JlZTUxMT...,Q1593292,World Golf Championships,One of four golf tournaments,He covers $T$ writes poetry about Rory McIlroy...,"The World Golf Championships,golf,WGC"
4,IjJlYWU1MDU0MThkZDJiNzNhNDZmOTY3OWY1N2JlZTUxMT...,Q2300345,Lucas Bjerregaard,Danish golfer,He covers $T$ writes poetry about Rory McIlroy...,"golfer,human,golf"

In [64]:
df

,id,entity_id,name,description,text,references
0,ImNhNjhiYjllYzkyMjU5MDJjOWYzZjQ5OTg4NDc3N2FjZD...,Q728646,partnership,arrangement in which parties agree to cooperat...,He is attending conference with his new $T$ Ca...,partner
1,ImNhNjhiYjllYzkyMjU5MDJjOWYzZjQ5OTg4NDc3N2FjZD...,Q5151,month,unit of time,After two $T$ in charge of the U.K. government...,months
2,ImNhNjhiYjllYzkyMjU5MDJjOWYzZjQ5OTg4NDc3N2FjZD...,Q30185,mayor,head of municipal government such as a town or...,After two months in charge of the U.K. governm...,Mayor
3,ImNhNjhiYjllYzkyMjU5MDJjOWYzZjQ5OTg4NDc3N2FjZD...,Q30185,mayor,head of municipal government such as a town or...,The Sunday Times reported last week that when ...,Mayor
4,ImNhNjhiYjllYzkyMjU5MDJjOWYzZjQ5OTg4NDc3N2FjZD...,Q5727902,circa,approximately – should be used with qualifier ...,After two months in charge of the U.K. governm...,"approximate value,approximately,ca.,around,abo..."
...,...,...,...,...,...,...
4,ImEwMjNiZGYzNjA1NzYxZmI2ZTY4MDg3ZGExZWM4Y2RhMz...,Q317521,Elon Musk,None,Wedbush analyst Dan Ives thinks 5K to 7K vehic...,"actor,chief executive officer,X.com,Elon Musk'..."
5,ImEwMjNiZGYzNjA1NzYxZmI2ZTY4MDg3ZGExZWM4Y2RhMz...,Q317521,Elon Musk,None,Volume forecast by manufacturer (unadjusted fo...,"actor,chief executive officer,X.com,Elon Musk'..."
6,ImEwMjNiZGYzNjA1NzYxZmI2ZTY4MDg3ZGExZWM4Y2RhMz...,Q3884,Amazon,American electronic commerce and cloud computi...,Keep an eye on Intel (NASDAQ INTC ) and AMD (N...,"Diapers.com,Goodreads,Jeff Bezos,BigTechs,Amaz..."
7,ImEwMjNiZGYzNjA1NzYxZmI2ZTY4MDg3ZGExZWM4Y2RhMz...,Q3884,Amazon,American electronic commerce and cloud computi...,Xilinx CEO Victor Peng is set to give the keyn...,"Diapers.com,Goodreads,Jeff Bezos,BigTechs,Amaz..."
0,IjkwZTViYjNkYzZhYWMzNTZlNDEwOTRiOWZmZTc1MzVjZm...,Q1369832,purchasing,acquisition of goods or services by fiduciary ...,"Thanks to new scientific findings, becoming a ...","buy,purchase"

In [58]:
randoment = df.iloc[22]
print(randoment["name"])
randoment.references

LinkedIn

'lynda.com,Sunnyvale,Internet,Jeff Weiner,LinkedIn SlideShare,LinkedIn Corporation,Reid Hoffman,linkedin.com,Mountain View,Microsoft'

`instance_of`...
people:
- human
- 

companies:
- business
- industry

locations:
- country
- city
- sovereign state
- big city
- 

products:
- software
- 

others:
- academic discipline
- profession

In [97]:
jsonfile = "../graphql/downloads/sports/2020_Q1.json"
rels = set()
from collections import defaultdict
countrels = defaultdict(int)

instance_of_inspector = set()

with open(jsonfile, 'r', encoding="utf8") as f:
    f = json.load(f)
    edges = f["events"]["edges"]

    entities = []
    texts = []

    for node in edges:
        node = node["node"]
        #print(node)
        for egs in node["entities"]:
            for ent in node["entities"][egs]:
                try:
                    tmp_rels = ent["node"]["relations"]["edges"]
                    for tr in tmp_rels:
                        _typ = tr["relationship"]["name"]
                        if "instance_of" in _typ:
                            #rels.add(tr["node"]["name"])
                            typname = tr["node"]["name"]
                            countrels[typname] += 1
                            
                            if "activity" in typname.lower():
                                instance_of_inspector.add(ent["node"]["name"])
                    
                except:
                    pass
                        
        
for k,v in sorted(countrels.items(), key=lambda x: -x[1]):
    print(k,v)

concept 182
academic discipline 170
unit of time 153
natural number 99
taxon 91
unit without standard conversion to SI 80
calendar month 73
even number 69
Fibonacci number 68
language 64
prime number 62
Fibonacci prime 61
Cantor number 58
occupation 53
type of sport 52
power of two 51
sovereign state 49
polyphyletic group of organisms known by one particular common name 45
profession 43
term 43
point in time with respect to recurrent timeframe 43
country 42
magic number 39
state of the United States 38
pronic number 36
composite number 35
day of the week 34
non-SI unit mentioned in the SI 33
Motzkin number 33
Bell number 33
factorial prime 33
taxicab number 33
Perrin number 33
Eisenstein prime 33
Sophie Germain prime 33
body fluid 33
economic branch 31
modern language 31
odd number 30
value 30
activity 29
business 29
Fermat number 28
recurring event 27
Mersenne number 26
economic activity 25
abstract object 25
Mersenne prime 25
triangular number 25
board game 24
unit of measurement 23
parts-per notation 23
quality 23
philosophical concept 23
square number 23
cube 22
positive emotion 19
road type 19
industry 19
music term 19
property 18
position 18
economic unit 18
need 18
goods 18
economic concept 16
specialty 16
power of 10 15
power of 1000 15
big city 15
software 14
human 14
virtue 13
financial measure 13
academic major 13
anatomical structure 13
deficient number 13
strictly non-palindromic number 13
intensive quantity 13
federal state 12
literary genre 12
definition 12
economic sector 12
media 12
Wikidata metaclass 12
anime television series 12
tetrahedral number 12
centered triangular number 12
city 12
areal quantity 12
association football position 11
genre 11
book series 11
contract 11
chemical element 10
sixth power 10
word 10
emotion 10
branch of biology 10
software category 10
first principle 10
conjunction 9
preposition 9
punctuation mark 9
legal concept 9
political concept 9
capital 9
kinship 9
branch of science 8
constitutional monarchy 8
word class 8
sense 8
computer network protocol 8
simple substance 8
verb 8
automorphic number 8
natural language 8
studio album 7
ordered pair 7
scalar magnitude 7
occurrence 7
first-order metaclass 7
noun 7
subordinator 7
build automation 7
off-side rule language 7
octagonal number 7
constitutional republic 7
democratic republic 7
continent 7
biological process 7
standard UNIX utility 6
newspaper 6
brand 6
hyperoperation 6
programming language 6
heptagonal pyramidal number 6
centered heptagonal number 6
Leyland number 6
facility 6
republic 6
geographic region 6
type of statistic 5
umbrella term 5
symptom 5
daily newspaper 5
computer science term 5
law 5
role 5
scripting language 5
scalar physical quantity 5
extensive quantity 5
common year starting on Sunday 5
common year 5
field of work 5
island nation 5
pentatope number 5
sociological concept 5
population group 5
continental area and surrounding islands 5
year 4
geography term 4
science 4
mental process 4
job 4
economic relation 4
physical quantity 4
administrative territorial entity 4
mode of transport 4
disease 4
largest city 4
nonprofit organization 4
city of the United States 4
centered square number 4
pentagonal number 4
square pyramidal number 4
centered tetrahedral number 4
corporate title 4
enterprise 4
Mediterranean country 4
Commonwealth realm 4
icositetragonal number 4
numeral 4
gift 3
stock market index 3
currency 3
state 3
technical standard 3
personality trait 3
filmmaking occupation 3
mathematical object 3
terminal pager 3
free software 3
musical notation 3
news agency 3
variable-order metaclass 3
film 3
drug 3
human behaviour 3
National Central City 3
direct-controlled municipality 3
sports league 2
political alignment 2
sport 2
type of French administrative division 2
stock exchange 2
macroeconomic indicator 2
geometric concept 2
condition 2
rugby union governing body 2
Wikidata end cause 2
mathematical concept 2
independent agency of the United States government 2
technological component 2
island 2
moraine 2
organization 2
aircraft component 2
right to petition 2
civic right 2
religion or world view 2
life style 2
Mars rover 2
solar vehicle 2
village in India 2
American football team 2
technique 2
team sport 2
public company 2
macrolanguage 2
colonial power 2
sexual orientation 2
status 2
social issue 2
bus 2
coin 2
frame of reference 2
psychology terminology 2
basic emotion 2
negative emotion 2
unitary state 2
sports discipline 2
art genre 2
nationality 2
key event 2
television station 2
athletic conference 1
high school 1
third-person pronoun 1
public educational institution of the United States 1
public research university 1
association football club 1
personal pronoun 1
economics term 1
tournament system 1
bus type 1
baseball position 1
data collection system 1
social networking service 1
blanket terminology 1
engineering 1
leap year 1
ratio 1
accounting term 1
retail 1
phenomenon 1
collectible 1
legal tender 1
positive power of ten 1
province of Canada 1
concept in physics 1
public health intervention 1
taxonomic rank 1
rank (zoology) 1
rank 1
function word 1
maniobra militar 1
designation for an administrative territorial entity 1
international sport governing body 1
sports governing body 1
meta-organization 1
recurring sporting event 1
legal status 1
heptagonal number 1
centered hexagonal number 1
centered octahedral number 1
Woodall number 1
double Mersenne number 1
hexagonal pyramidal number 1
structural element 1
manga series 1
classification in sports 1
association football league 1
association football team 1
landlocked country 1
chairperson 1
mass media 1
parent-child relationship 1
nominal kinship 1
American football position 1
sports terminology 1
sports organization 1
region of France 1
United States federal agency 1
biome 1
type of map 1
video game 1
state with limited recognition 1
health problem 1
chemical compound 1
type of economical interaction 1
political territorial entity 1
literary work 1
resource 1
meteorological phenomenon 1
private not-for-profit educational institution 1
private university 1
time zone 1
month starting on Tuesday 1
calendar month of a given year 1
January 1
price 1
boolean function 1
logical connective 1
decimal currency 1
commercial organization 1
public policy 1
literary form 1
class of award 1
universal language 1
centered octagonal number 1
centered cube number 1
nonagonal number 1
sports agency 1
subcontinent 1
transcontinental country 1
country of origin 1
municipality 1
field of study 1
open-access publisher 1
city with millions of inhabitants 1
animated feature film 1
construct 1
billionaire 1
perfect number 1
item 1
computer network 1
architectural structure 1
vehicle 1
regulation of the European Parliament and of the Council 1
written work 1
fantastique genre 1
type of business entity in the USA 1
television channel 1
type of business entity 1
juridical person 1
intergovernmental organization 1
social status 1

In [96]:
instance_of_inspector

{'advertising',
 'construction',
 'consulting company',
 'eating',
 'help',
 'inquiry',
 'management',
 'manufacturing',
 'marketplace',
 'mining',
 'sales',
 'social media',
 'teaching',
 'telecommunication',
 'valuation'}

In [107]:
jsonfile = "../graphql/downloads/tech/2019_Q1.json"
rels = set()
from collections import defaultdict
countrels = defaultdict(int)

instance_of_inspector = set()

with open(jsonfile, 'r', encoding="utf8") as f:
    f = json.load(f)
    edges = f["events"]["edges"]

    entities = []
    texts = []

    for node in edges:
        node = node["node"]
        #print(node)
        for egs in node["entities"]:
            for ent in node["entities"][egs]:
                try:
                    tmp_rels = ent["node"]["relations"]["edges"]
                    for tr in tmp_rels:
                        _typ = tr["relationship"]["name"]
                        if "subclass_of" in _typ:
                            #rels.add(tr["node"]["name"])
                            typname = tr["node"]["name"]
                            countrels[typname] += 1
                            
                            if "nominal good" in typname.lower():
                                instance_of_inspector.add(ent["node"]["name"])
                    
                except:
                    pass
                        
        
for k,v in sorted(countrels.items(), key=lambda x: -x[1]):
    print(k,v)

FileNotFoundError: [Errno 2] No such file or directory: '../graphql/downloads/tech/2019_Q1.json'

In [104]:
instance_of_inspector

{'money'}

In [109]:
df = pd.read_csv(os.path.join(save_folder, "no limit", "tech_entities.csv"), index_col=0)
df.head()

,id,entity_id,name,description,text,references
0,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q1370,Virginia,state of the United States of America,The APRES 50th annual meeting will take place ...,"Richmond,Government of Virginia,Commonwealth o..."
1,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q83440,country music,genre of American popular music,The APRES 50th annual meeting will take place ...,"country & western,country and western,country,..."
2,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q8434,education,learning in which knowledge and skills are tra...,Did you know the American peanut has a society...,"parenting,academic discipline,Education,Educat..."
3,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q8434,education,learning in which knowledge and skills are tra...,According to the 1969 Journal of American Pean...,"parenting,academic discipline,Education,Educat..."
4,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q8434,education,learning in which knowledge and skills are tra...,"1, In July 1968, as a result of a lot of hard ...","parenting,academic discipline,Education,Educat..."

In [110]:
df.describe()

,id,entity_id,name,description,text,references
count,93036,93036,93036,91699,93036,93036
unique,922,4077,4060,3541,20701,5610
top,IjFiMTI4NzRhNTRkZjBjNzU1MmEwYTZmZWViZmUzNjE0MT...,Q11016,technology,"making, modification, usage, and knowledge of ...","Newsweek provides the latest news, in-depth an...","technological,academic discipline,Technology,T..."
freq,1420,2427,2427,2427,228,2427

In [111]:
entities = df.name.unique()

In [112]:
entities[1900:1950]

array(['Credit Suisse', '21 Club', 'Adobe Photoshop', 'pornography',
       'pornographic film', 'image', 'Mobile World Congress', 'Cameroon',
       'South Africa', 'domain name registrar', 'real estate broker',
       'January', 'Fannie May', 'Keebler Company', 'snack',
       'breakfast cereal', 'Direct Stream Digital', 'Kraft Heinz',
       'tert-butylhydroquinone', 'Campbell Soup Company', 'fad',
       'Cloverhill Bakery', 'cocoa bean', 'universal quantification',
       'magnetic-core memory',
       'Cooperation Council for the Arab States of the Gulf', 'Careem',
       'board of directors', 'Strathclyde', 'Leidos', 'Scotland',
       'Scottish people', 'University of Glasgow', 'military tactics',
       'live action role-playing game', 'waste',
       'extra-vehicular activity', 'extrasolar planet', 'space suit',
       'Transiting Exoplanet Survey Satellite', 'light-year', 'Croatia',
       'cloud', 'river', 'reactionary', 'Valencia', 'digital certificate',
       'N T Rama Rao filmography', 'Madrid', 'money laundering'],
      dtype=object)

In [128]:
df = pd.read_csv(os.path.join(save_folder, "tech_entities.csv"), index_col=0)
df.head()

,id,entity_id,name,description,text,references
0,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q1370,Virginia,state of the United States of America,The APRES 50th annual meeting will take place ...,"Old Dominion,Ralph Northam,Virginia, United St..."
1,IjcyMTY4NmNjYjU2N2RjZDY5OTA5YzI1YTk3NzlmODY0MG...,Q501542,United States Department of Agriculture,department of United States government respons...,And those members come from $T$ land-grant and...,"Jamie L. Whitten Building,Sonny Perdue,Henry L..."
0,IjE4YjZmMDhjNmJkNDEwYjBjMTM3OWMzMjgxMzk1ZmYxND...,Q2283,Microsoft,American multinational technology corporation,"In addition, 70 of that revenue was recurring,...","Microsoft Casual Games,Windows Media Player,Sy..."
1,IjE4YjZmMDhjNmJkNDEwYjBjMTM3OWMzMjgxMzk1ZmYxND...,Q2283,Microsoft,American multinational technology corporation,Chen quickly proceeded to turn things around b...,"Microsoft Casual Games,Windows Media Player,Sy..."
2,IjE4YjZmMDhjNmJkNDEwYjBjMTM3OWMzMjgxMzk1ZmYxND...,Q2283,Microsoft,American multinational technology corporation,"For example, the Microsoft deal has the potent...","Microsoft Casual Games,Windows Media Player,Sy..."

In [129]:
df.describe()

,id,entity_id,name,description,text,references
count,17369,17369,17369,17261,17369,17369
unique,778,807,806,734,4574,1106
top,IjZjZDYxZjM3NmE3MGZjM2YwMjlhMGUwNzkzNTUzZDAyNm...,Q668,India,federal republic in South Asia,Click here to find out how you can get the $T$...,"Republic of India,Bharat,sovereign state,IN,🇮🇳..."
freq,140,1791,1791,1791,18,1791

In [131]:
entities = df.name.unique()
entities[100:200]

array(['Cambridge Analytica', 'SCL Group',
       'Massachusetts Institute of Technology', 'The Founder',
       'Las Vegas', 'National Aeronautics and Space Administration',
       'plant', 'Agence France-Presse', 'The Wall Street Journal',
       'Academy Awards', 'Salesforce.com', 'NVIDIA', 'County Mayo',
       'Pinnipedia', 'George VI', 'Mergenthaler Linotype Company',
       'Mark Zuckerberg', 'Facebook', 'Nevada',
       'Internet Systems Consortium', 'JetBlue Airways',
       'Applied Materials', 'Fitbit Inc.', 'renminbi',
       'New York Stock Exchange', 'Sweden', 'functional group',
       'Jesus Christ', 'binary search tree', 'Gloria Steinem',
       'National Collegiate Athletic Association',
       'Georgetown University',
       'University of Maryland, Baltimore County', 'Culicidae', 'Danone',
       'Teuthida', 'infrared radiation', 'Sundar Pichai',
       'Impact Technology Development (United States)', 'California',
       'Francisco Franco', 'Qinetiq',
       'United States Department of Commerce', 'Kpmg AS',
       'University of Oklahoma', 'F-14 Tomcat', 'Abraham Lincoln',
       'charitable organization', 'Democratic Party',
       'World Health Organization', 'Conagra Brands Inc.', 'Reading F.C.',
       'Toronto Stock Exchange', 'Washington, D.C.',
       'Technical University of Munich', 'Arrested Development',
       'Kirundo Airport', 'PricewaterhouseCoopers AS',
       'implantation of human embryos', 'tennis court', 'Higashidōri',
       'S.C. Corinthians Paulista', 'Visa Inc.', 'Mastercard',
       'HM Revenue and Customs', 'Free Syrian Army', 'Financial Times',
       'London Metal Exchange', 'film producer',
       'Newfoundland and Labrador', 'Snap Inc.', 'Elon Musk',
       'Indian Space Research Organisation', 'Bloomberg L.P.',
       'Harrison Schmitt', 'Mercedes-Benz', 'Daimler AG', 'linguistics',
       'World Wide Web', 'genocide', 'Silicon Graphics',
       'Advanced Audio Coding', 'United Nations', 'Chevron Corporation',
       'Royal Dutch Shell', 'Norway', 'Equinor ASA', 'The Firm',
       'Indonesia', 'Italy', 'Georgia', 'Israel Aerospace Industries',
       'Polaris Industries', 'Japanese yen', 'Indian Motorcycle',
       'Blockbuster LLC', 'Arnold Schwarzenegger',
       'United Parcel Service', 'car', 'Nebraska'], dtype=object)